[package]
name = "rust-profanos"
version = "1.0.2"
edition = "2024"
license = "MIT"
description = "A lib to be able to code in rust into profanOS"

[dependencies]

[lib]
test = false
crate-type = ["rlib"]